language: java
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r jacoco.xml

